# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlereviewvote',
            unique_together=set([('user', 'review')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationreviewvote',
            unique_together=set([('user', 'review')]),
        ),
    ]
