# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('articles', '0001_initial'),
        ('votes', '0002_auto_20160727_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereviewvote',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationreviewvote',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
