# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20160727_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereviewvote',
            name='article',
        ),
        migrations.RemoveField(
            model_name='organizationreviewvote',
            name='organization',
        ),
    ]
