# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bio',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
