# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=2083, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('P', 'Positive'), ('N', 'Neutral'), ('C', 'Critical')], default='N', max_length=1)),
                ('text', models.CharField(max_length=3000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('contributors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('original_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_original_author_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083, unique=True)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
