# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=2083, unique=True)),
                ('image_url', models.CharField(max_length=2083)),
                ('keywords', models.CharField(max_length=5000)),
                ('related_articles', models.ManyToManyField(blank=True, to='articles.Article')),
            ],
        ),
    ]
