# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 21:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=2083, unique=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('date', models.DateTimeField(null=True)),
                ('related_articles', models.ManyToManyField(blank=True, to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083, unique=True)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
