# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
    ]
