# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlereview',
            old_name='organization',
            new_name='article',
        ),
    ]
