# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20160725_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleInProgress',
            new_name='PageInProgress',
        ),
        migrations.RemoveField(
            model_name='article',
            name='related_articles',
        ),
    ]
