# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedorganizationdomainremoval',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationdomainremoval',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationedit',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationedit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationreviewedit',
            name='review',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationreviewedit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organizationreview',
            name='user',
        ),
        migrations.AddField(
            model_name='organizationreview',
            name='contributors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationreview',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoggedOrganizationDomainRemoval',
        ),
        migrations.DeleteModel(
            name='LoggedOrganizationEdit',
        ),
        migrations.DeleteModel(
            name='LoggedOrganizationReviewEdit',
        ),
    ]
