# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationreview',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
