# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_loggedorganizationreviewedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedorganizationedit',
            name='edit_hash',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggedorganizationreviewedit',
            name='edit_hash',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
