# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_auto_20160725_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationreview',
            name='original_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='original_author_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationreview',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
