# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20160801_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='url',
            new_name='homepage',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='wiki',
        ),
        migrations.AddField(
            model_name='organizationwiki',
            name='wiki',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.OrganizationWiki'),
            preserve_default=False,
        ),
    ]
