# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20160801_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationwiki',
            name='wiki',
        ),
        migrations.AddField(
            model_name='organizationwiki',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
