# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedorganizationdomainaddition',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationdomainaddition',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='loggedorganizationdomainaddition',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoggedOrganizationDomainAddition',
        ),
    ]
