# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20160725_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationdomain',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='domains',
            field=models.ManyToManyField(to='organizations.OrganizationDomain'),
        ),
    ]
