# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20160725_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='domains',
        ),
        migrations.AddField(
            model_name='organizationdomain',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
