# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organizationcomment_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcomment',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
