# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20160620_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationComment',
            new_name='OrganizationReview',
        ),
    ]
