# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20160802_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='wiki',
        ),
        migrations.AddField(
            model_name='organizationwiki',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
