# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20160802_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationwiki',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 5, 1, 0, 13, 121879)),
        ),
        migrations.AlterField(
            model_name='organizationwiki',
            name='time_last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
