# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20160805_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationwiki',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 5, 7, 9, 34, 627677, tzinfo=utc)),
        ),
    ]
