# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20160805_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationwiki',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
