# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160805_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 5, 1, 0, 13, 126038)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 5, 1, 0, 13, 125286)),
        ),
    ]
