# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_commentreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='commentreply',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
