# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='')),
                ('info_url', models.CharField(max_length=2083)),
                ('child_organizations', models.ManyToManyField(blank=True, to='dashboard.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='site_urls',
            field=models.ManyToManyField(to='dashboard.OrganizationURL'),
        ),
    ]
