# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationurl',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='site_urls',
            field=models.ManyToManyField(to='dashboard.OrganizationURL'),
        ),
    ]
