# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160529_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='child_organizations',
            field=models.ManyToManyField(blank=True, related_name='parent_organizations', to='dashboard.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationdomain',
            name='domain',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
